
version: '3.8' 

services:
  # Servicio de la base de datos PostgreSQL
  postgres_db:
    image: postgres:14.3-alpine # Imagen oficial de PostgreSQL, versión 14.3 (alpine es más ligera)
    container_name: medkirindb # Nombre del contenedor para fácil referencia
    restart: always # Reinicia el contenedor si se detiene, a menos que se detenga manualmente
    environment:
      # Credenciales para la base de datos (¡Cámbialas en producción!)
      #POSTGRES_USER: tu_usuario_db # Reemplaza con tu nombre de usuario deseado
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Reemplaza con tu contraseña deseada
      POSTGRES_DB: ${DB_NAME} # Reemplaza con el nombre de tu base de datos
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=es_VE.UTF-8 --lc-ctype=es_VE.UTF-8 --locale=es_VE.UTF-8"
      LANG: es_VE.UTF-8 
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    healthcheck: # Opcional: verifica que la base de datos esté lista
      test: ["CMD-SHELL", "pg_isready -U tu_usuario_db -d tu_nombre_db"]
      interval: 10s
      timeout: 5s
      retries: 5

# Definición de volúmenes nombrados
volumes:
  postgres_data: {} # El driver por defecto es 'local'